spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=smart_shop;trustServerCertificate=true;sendStringParametersAsUnicode=true
spring.datasource.username=sa
spring.datasource.password=12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.open-in-view=false

jwt.secret=tennyhoang-super-secret-key-32chars!!
jwt.expiration=86400000

groq.api.key=your-groq-api-key-here
server.port=8080
